#!/usr/bin/env bash

scptid="me.elethom.updatekexts"
rm -rf /tmp/$scptid
mkdir -p /tmp/$scptid

shopt -s globstar # **

for file in /Volumes/EFI/EFI/OC/Kexts/*.kext/Contents/Info.plist
do
    filename=$(echo "$file" | grep -Po "Kexts/\K.*?.kext")
    name=$(grep -Pzo "(?s)CFBundleName.*?<string>\K(.*?)(?=</string>)" "$file")
    version=$(grep -Pzo "(?s)CFBundleVersion.*?<string>\K(.*?)(?=</string>)" "$file")
    case "$name" in
        "AppleALC") path="acidanthera/AppleALC"
            ;;
        "IntelMausi") path="acidanthera/IntelMausi"
            ;;
        "Lilu") path="acidanthera/Lilu"
            ;;
        "NVMeFix") path="acidanthera/NVMeFix"
            ;;
        "VirtualSMC") path="acidanthera/VirtualSMC"
            ;;
        "WhateverGreen") path="acidanthera/WhateverGreen"
            ;;
        *) continue
            ;;
    esac
    latest=$(curl --silent "https://api.github.com/repos/$path/releases/latest" | grep -Po '"tag_name": *"\K.*?(?=")')
    if [ "$version" != "$latest" ]; then
        if [ ! -f "/tmp/$scptid/$name$latest.zip" ]; then
            download=$(curl --silent "https://api.github.com/repos/$path/releases/latest" | grep -Po '"browser_download_url": *"\K((?!DEBUG).)*?(?=")')
            curl -L "$download" > "/tmp/$scptid/$name$latest.zip"
        fi
        bsdtar -C /tmp/$scptid/ -xf "/tmp/$scptid/$name$latest.zip" "**.kext"
        echo "$name\t$(tput tbc; tput hts)$version > $latest"
    else
        echo "$name\t$(tput tbc; tput hts)$version is latest"
    fi
done

cp -r /tmp/$scptid/**/*.kext /Volumes/EFI/EFI/OC/Kexts/
echo "All kexts updated!"
